version: '3.5'
services:
  db:
    container_name: nautec_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: postsdb
    ports:
      - 3306:3306